language: php

install:
  - bin/install-composer.php
  - php -r "unlink('composer-setup.php');"
  - travis_wait php composer.phar install --no-interaction
  - mkdir -p build/logs

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

dist: trusty
sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise

matrix:
  allow_failures:
    - php: hhvm

script:
  - vendor/bin/phpunit

after_script:
  - travis_retry bin/coveralls.sh