language: php

install:
  - mkdir -p build/logs
  - mv .git ~.git

dist: trusty
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - hhvm-nightly

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  include:
    - php: 5.3
      dist: precise
      env: DEPENDENCIES="high"

    - php: 5.3
      dist: precise
      env: DEPENDENCIES="low"

    - php: hhvm
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-3.12
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-3.15
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-3.18
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-nightly
      env: DEPENDENCIES="hhvm_high"

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'hhvm_high' ]]; then bin/composer-set-config.php php 7.0 && travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi

before_script:
  - if [[ "$DEPENDENCIES" = 'hhvm_high' ]]; then echo 'hhvm.php7.all=1' >> /etc/hhvm/php.ini; fi

script:
  - vendor/bin/phpunit

after_script:
  - mv ~.git .git
  - travis_retry bin/coveralls.sh
