language: php

install:
  - mkdir -p build/logs
  - mv .git ~.git

dist: trusty
sudo: false

php:
  - 5.4
#  - 5.5
#  - 5.6
#  - 7.0
#  - 7.1
#  - nightly
#  - hhvm
#  - hhvm-3.3
#  - hhvm-3.6
#  - hhvm-3.9
#  - hhvm-3.12
#  - hhvm-3.15
#  - hhvm-3.18
#  - hhvm-nightly

matrix:
  include:
    - php: 5.3
      dist: precise
    - php:
      - hhvm
      - hhvm-3.12
      - hhvm-3.15
      - hhvm-3.18
      - hhvm-nightly
      env: HHVM_PHP7=1

before_script:
  - if [ ${HHVM_PHP7+x} ]; then echo 'hhvm.php7.all=1' >> /etc/hhvm/php.ini; fi

script:
  - php -r "echo phpversion() . PHP_EOL;"
  - travis_wait composer update --prefer-lowest --no-interaction && php -d hhvm.jit=0 -d error_reporting=$(php -r "var_export(E_ALL & ~E_DEPRECATED);") vendor/bin/phpunit
  - travis_wait composer update --no-interaction && php -d hhvm.jit=0 vendor/bin/phpunit

after_script:
  - mv ~.git .git
  - travis_retry bin/coveralls.sh
