language: php

install:
  - mkdir -p build/logs
  - mv .git ~.git

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

script:
  - travis_wait composer update --prefer-lowest --no-interaction && bin/phpunit.sh
  - travis_wait composer update --no-interaction && bin/phpunit.sh

after_script:
  - mv ~.git .git
  - travis_retry bin/coveralls.sh
