language: php

install:
  - mkdir -p build/logs
  - mv .git ~.git

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - hhvm-nightly

matrix:
  include:
    - php: 5.3
      dist: precise

script:
  - php -r "echo phpversion() . PHP_EOL;"
  - travis_wait composer update --prefer-lowest --no-interaction && php -d error_reporting=$(php -r "var_export(E_ALL & ~E_DEPRECATED);") vendor/bin/phpunit $(php -r "echo defined('HHVM_VERSION')?'--no-coverage':'';")
  - travis_wait composer update --no-interaction && vendor/bin/phpunit $(php -r "echo defined('HHVM_VERSION')?'--no-coverage':'';")
  - travis_wait bin/hhvm-travis.sh

after_script:
  - mv ~.git .git
  - travis_retry bin/coveralls.sh
